@extends('layouts.customer')

@section('title', 'Notifications')

@section('content')
    <div class="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8">
        <x-ui.page-header
            eyebrow="Updates"
            title="Notifications"
            description="Booking confirmations, reminders, salon updates and promos — all in one place."
        />

        <x-ui.alert type="info" class="mb-6">
            These notifications are generated by the system. You can read and dismiss them, but you
            cannot edit or create them.
        </x-ui.alert>

        @include('customer.notifications._list')
    </div>
@endsection
