<?php

namespace Tests\Feature;

use App\Enums\AppointmentStatus;
use App\Notifications\AppointmentConfirmedNotification;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * The app has one success style: the floating toast.
 *
 * There used to be two — this, and a `x-ui.alert type="success"` banner pinned
 * at the top of the page. These tests lock the consolidation so the split does
 * not come back one call site at a time.
 */
class FlashToastTest extends TestCase
{
    use RefreshDatabase;

    /* ------------------------------------------------------------------ */
    /* The banner is gone everywhere                                        */
    /* ------------------------------------------------------------------ */

    public function test_the_notifications_page_no_longer_shows_the_info_banner(): void
    {
        $user = $this->makeUser();

        // With something unread, so the list renders and the rest-of-the-page
        // assertions mean something.
        $user->notify(new AppointmentConfirmedNotification($this->makeAppointment($user)));

        $html = $this->actingAs($user)
            ->get(route('notifications.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringNotContainsString('These notifications are generated by the system', $html);

        // The rest of the page is untouched. The status line stands in for it:
        // it is what the list renders for an appointment notification, so
        // finding it means the page built, paginated and listed.
        $this->assertStringContainsString('>Notifications</h1>', $html);
        $this->assertStringContainsString('Appointment status updated: Confirmed', $html);
    }

    /**
     * The bell is the read receipt now, so the page no longer flashes
     * anything — the confirmation was for a button that no longer exists.
     */
    public function test_marking_all_read_does_not_flash_a_message(): void
    {
        $user = $this->makeUser();
        $user->notify(new AppointmentConfirmedNotification($this->makeAppointment($user)));

        $this->actingAs($user)
            ->patch(route('notifications.read-all'))
            ->assertRedirect(route('notifications.index'))
            ->assertSessionMissing('status')
            ->assertSessionMissing('toast');
    }

    public function test_no_layout_renders_a_success_banner_any_more(): void
    {
        $admin = $this->makeAdmin();
        $user = $this->makeUser();

        $adminPages = [
            route('admin.appointments.index'),
            route('admin.services.index'),
            route('admin.reports.index'),
            route('admin.inventory.index'),
            route('admin.appointments.archived'),
        ];

        foreach ($adminPages as $url) {
            $html = $this->actingAs($admin, 'admin')->get($url)->assertOk()->getContent();

            $this->assertStringNotContainsString("session('status')", $html, "{$url} still reads the status flash.");
            $this->assertStringNotContainsString('ui.alert', $html, "{$url} still renders a banner.");
        }

        foreach ([route('appointments.index'), route('notifications.index'), route('appointments.index')] as $url) {
            $html = $this->actingAs($user)->get($url)->assertOk()->getContent();

            $this->assertStringNotContainsString("session('status')", $html, "{$url} still reads the status flash.");
            $this->assertStringNotContainsString('ui.alert', $html, "{$url} still renders a banner.");
        }
    }

    /* ------------------------------------------------------------------ */
    /* Every flash reaches the toast                                        */
    /* ------------------------------------------------------------------ */

    /**
     * The plain `status` string that most controllers flash is now rendered by
     * the same component as the structured `toast` — no controller rewrite, and
     * nothing silently lost.
     */
    public function test_a_plain_status_flash_renders_as_a_success_toast(): void
    {
        $html = $this->withSession(['status' => 'All notifications marked as read.'])
            ->actingAs($this->makeAdmin(), 'admin')
            ->get(route('admin.appointments.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('All notifications marked as read.', $html);
        $this->assertStringContainsString('data-toast', $html);
        // The solid green success fill, not the old light-green banner.
        $this->assertStringContainsString('bg-status-completed', $html);
    }

    public function test_a_structured_toast_still_renders(): void
    {
        $message = 'Appointments must be booked at least one day in advance.';

        $html = $this->withSession(['toast' => ['type' => 'warning', 'message' => $message]])
            ->actingAs($this->makeAdmin(), 'admin')
            ->get(route('admin.dashboard'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString($message, $html);
        $this->assertStringContainsString('bg-status-low-stock', $html);
    }

    /**
     * An action that flashed both keys must still produce exactly one toast.
     * `toast` wins, because it is the one that carries a tone.
     */
    public function test_both_flash_keys_at_once_produce_a_single_toast(): void
    {
        $html = $this->withSession([
            'toast' => ['type' => 'success', 'message' => 'Structured message.'],
            'status' => 'Plain message.',
        ])
            ->actingAs($this->makeAdmin(), 'admin')
            ->get(route('admin.dashboard'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('Structured message.', $html);
        $this->assertStringNotContainsString('Plain message.', $html);

        $this->assertSame(
            1,
            substr_count($html, 'aria-live="polite"'),
            'Exactly one toast should have been rendered.',
        );
    }

    public function test_the_toast_container_is_mounted_once_per_page(): void
    {
        $html = $this->actingAs($this->makeUser())->get(route('appointments.index'))->assertOk()->getContent();

        // Counted on the listener attribute rather than the container's name,
        // which also appears inside the bus script as a querySelector target.
        $this->assertSame(1, substr_count($html, 'x-on:bta:toast.window='));
    }

    /* ------------------------------------------------------------------ */
    /* The dismissal is the same either way                                 */
    /* ------------------------------------------------------------------ */

    public function test_a_flashed_toast_is_dismissible_and_fades(): void
    {
        $html = $this->withSession(['status' => 'Saved.'])
            ->actingAs($this->makeAdmin(), 'admin')
            ->get(route('admin.appointments.index'))
            ->assertOk()
            ->getContent();

        // A close button, wired through the shared bus rather than a bare
        // remove, so a manual dismissal fades like the automatic one.
        $this->assertStringContainsString('aria-label="Dismiss notification"', $html);
        $this->assertStringContainsString('window.btaToast.dismiss(', $html);
    }

    /**
     * Blade compiles `@class`, `@checked`, `@disabled` and a handful of other
     * directives, and leaves every other `@word` as literal text. `@click` is
     * not one of them, so the toast's close button was written with a handler
     * that never reached the browser.
     *
     * Scoped to the toast: the same shorthand is (separately, and pre-existing)
     * used by the nav dropdown and the admin table pager, which is a wider fix
     * than this task.
     */
    public function test_the_toast_dismiss_button_uses_a_compiled_handler(): void
    {
        // Comments stripped first: the component explains the shorthand in prose,
        // and that prose mentions `@click`.
        $component = preg_replace(
            '/\{\{--.*?--\}\}/s',
            '',
            file_get_contents(resource_path('views/components/ui/toast.blade.php')),
        );

        $this->assertDoesNotMatchRegularExpression('/@click/', $component);
        $this->assertStringContainsString('x-on:click="window.btaToast.dismiss(', $component);

        $html = $this->withSession(['status' => 'Saved.'])
            ->actingAs($this->makeUser())
            ->get(route('appointments.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('aria-label="Dismiss notification"', $html);
        $this->assertStringContainsString('x-on:click="window.btaToast.dismiss(', $html);
    }

    /* ------------------------------------------------------------------ */
    /* Real actions, end to end                                             */
    /* ------------------------------------------------------------------ */

    public function test_the_real_producers_all_reach_the_toast(): void
    {
        $admin = $this->makeAdmin();
        $user = $this->makeUser();

        // Customer: profile update — a plain `status` string.
        $message = $this->actingAs($user)
            ->from(route('profile.edit'))
            ->patch(route('profile.update'), [
                'first_name' => 'Updated',
                'last_name' => 'Name',
                'email' => $user->email,
                'username' => $user->username,
                'contact_number' => $user->contact_number,
            ])
            ->assertSessionHas('status')
            ->getSession()
            ->get('status');

        $this->assertSame('Your profile has been updated.', $message);

        // Admin: an appointment status change.
        $appointment = $this->makeAppointment($user, null, ['status' => AppointmentStatus::Pending]);

        $status = $this->actingAs($admin, 'admin')
            ->patch(route('admin.appointments.status', $appointment), ['status' => 'confirmed'])
            ->getSession()
            ->get('toast');

        $this->assertSame(['type' => 'success', 'message' => 'Appointment accepted.'], $status);

        // Customer: cancelling an appointment, a plain `status` string.
        $cancelled = $this->makeAppointment($user, null, [
            'status' => AppointmentStatus::Pending,
            'customer_phone' => '09171234567',
        ]);

        $message = $this->actingAs($user)
            ->from(route('appointments.index', ['view' => $cancelled->id]))
            ->patch(route('appointments.cancel.update', $cancelled), [
                'reason_preset' => 'Schedule conflict',
                'agree_cancellation_policy' => '1',
            ])
            ->assertSessionHas('status')
            ->getSession()
            ->get('status');

        $this->assertStringContainsString('has been cancelled', $message);
    }

    /**
     * `show()` takes loose arguments; `render()` takes the `bta:toast` event
     * payload. They were aliased, so every toast raised from JavaScript — the
     * appointment status error in `app.js` included — rendered with an empty
     * body.
     */
    public function test_the_bus_exposes_show_separately_from_render(): void
    {
        $stack = file_get_contents(resource_path('views/components/ui/toast-stack.blade.php'));

        $this->assertStringContainsString('function show(type, message, duration)', $stack);
        $this->assertStringContainsString('render({ type: type, message: message, duration: duration })', $stack);
        $this->assertStringContainsString('return { show: show, render: render, dismiss: dismiss }', $stack);
        $this->assertStringNotContainsString('show: render', $stack);

        // And the caller in app.js uses that two-argument form.
        $this->assertStringContainsString(
            "window.btaToast?.show('error', message)",
            file_get_contents(resource_path('js/app.js')),
        );
    }

    /**
     * The alert component lost its `success` variant on purpose — that is what
     * stops the page banner being reintroduced.
     */
    public function test_the_alert_component_no_longer_offers_a_success_style(): void
    {
        $component = file_get_contents(resource_path('views/components/ui/alert.blade.php'));

        $this->assertStringNotContainsString("'success' =>", $component);

        // The styles that remain are still in use.
        $this->assertStringContainsString("'error' =>", $component);
        $this->assertStringContainsString("'warning' =>", $component);
        $this->assertStringContainsString("'info' =>", $component);
    }
}
