<script setup>
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import Alert from '@/components/ui/Alert.vue';
import AppIcon from '@/components/ui/AppIcon.vue';
import EmptyState from '@/components/ui/EmptyState.vue';
import PageHeader from '@/components/ui/PageHeader.vue';
import {
    createdLabel,
    filterNotifications,
    markAllAsRead,
    markAsRead,
    notifications,
    unreadNotificationCount,
} from '@/data/notifications';
import { setFlash } from '@/lib/session';

/**
 * Customer Flow 9 — Notifications.
 *
 * Ported from `customer/notifications/index.blade.php` and its `_list` partial,
 * inlined the way `@include` used to inline it. The list is read-only: the only
 * writes are the two mark-as-read actions, and because `notifications` is a
 * reactive collection the unread pill and the counters update on their own.
 */

/** Icon + tone mapping shared with the payload written by the notifications. */
const ICONS = {
    calendar: 'calendar-days',
    check: 'check-circle',
    x: 'x-circle',
    bell: 'bell',
    star: 'star',
    sparkles: 'sparkles',
    gift: 'gift',
    clock: 'clock',
    heart: 'heart',
};

/** The `@class([...])` tone map from the partial, as a lookup. */
const TONES = {
    pending: 'bg-status-pending-bg text-status-pending',
    confirmed: 'bg-status-confirmed-bg text-status-confirmed',
    progress: 'bg-status-progress-bg text-status-progress',
    completed: 'bg-status-completed text-cream',
    cancelled: 'bg-status-cancelled-bg text-status-cancelled',
};

const route = useRoute();

/** Anything that is not `all` or `unread` falls back to `all`, as the controller did. */
const filter = computed(() => {
    const requested = String(route.query.filter ?? '');

    return ['all', 'unread'].includes(requested) ? requested : 'all';
});

const rows = computed(() => filterNotifications(filter.value));
const unreadCount = computed(() => unreadNotificationCount.value);
const totalCount = computed(() => notifications.length);

function isUnread(notification) {
    return !notification.read_at;
}

function toneClass(tone) {
    return TONES[tone] ?? 'bg-gold/20 text-gold-dark';
}

function read(notification) {
    markAsRead(notification.id);

    setFlash('Notification marked as read.');
}

function readAll() {
    markAllAsRead();

    setFlash('All notifications marked as read.');
}
</script>

<template>
    <div class="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8">
        <PageHeader
            eyebrow="Updates"
            title="Notifications"
            description="Booking confirmations, reminders, salon updates and promos — all in one place."
        />

        <Alert type="info" class="mb-6">
            These notifications are generated by the system. You can read and dismiss them, but you
            cannot edit or create them.
        </Alert>

        <div class="bta-card p-5">
            <!-- Header: filters + mark all read -->
            <div class="flex flex-wrap items-center justify-between gap-3 border-b border-primary/10 pb-4">
                <div class="flex gap-2">
                    <router-link
                        :to="{ name: 'notifications.index' }"
                        class="rounded-pill px-3.5 py-1.5 text-sm font-medium transition"
                        :class="filter === 'all' ? 'bg-primary text-cream' : 'bg-linen text-ink hover:bg-linen/70'"
                    >
                        All ({{ totalCount }})
                    </router-link>
                    <router-link
                        :to="{ name: 'notifications.index', query: { filter: 'unread' } }"
                        class="rounded-pill px-3.5 py-1.5 text-sm font-medium transition"
                        :class="filter === 'unread' ? 'bg-primary text-cream' : 'bg-linen text-ink hover:bg-linen/70'"
                    >
                        Unread ({{ unreadCount }})
                    </router-link>
                </div>

                <button v-if="unreadCount > 0" type="button" class="toggle-link" @click="readAll">
                    Mark all as read
                </button>
            </div>

            <!-- Read-only list; customers cannot compose or edit -->
            <div v-if="rows.length === 0" class="pt-6">
                <EmptyState
                    title="No notifications"
                    :description="filter === 'unread' ? 'You are all caught up.' : 'Booking updates and announcements will appear here.'"
                />
            </div>

            <ul v-else class="divide-y divide-primary/8">
                <li v-for="notification in rows" :key="notification.id" class="flex items-start gap-4 py-4">
                    <span
                        class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full"
                        :class="toneClass(notification.tone)"
                    >
                        <AppIcon :name="ICONS[notification.icon] ?? 'bell'" class="h-5 w-5" />
                    </span>

                    <div class="min-w-0 flex-1">
                        <div class="flex flex-wrap items-center gap-2">
                            <p class="text-sm font-semibold" :class="isUnread(notification) ? 'text-primary' : 'text-ink'">
                                {{ notification.title ?? 'Notification' }}
                            </p>

                            <span
                                v-if="isUnread(notification)"
                                class="h-2 w-2 rounded-full bg-primary"
                                title="Unread"
                            ></span>
                        </div>

                        <p class="mt-0.5 text-sm text-ink-muted">{{ notification.message ?? '' }}</p>
                        <p class="mt-1 text-xs text-ink-muted/80">{{ createdLabel(notification) }}</p>
                    </div>

                    <div class="flex shrink-0 flex-col items-end gap-1.5">
                        <router-link
                            v-if="notification.url"
                            :to="notification.url"
                            class="text-xs font-medium text-primary underline underline-offset-2 hover:text-primary-dark"
                        >View</router-link>

                        <button
                            v-if="isUnread(notification)"
                            type="button"
                            class="toggle-link"
                            @click="read(notification)"
                        >Mark read</button>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</template>
